export const PATH = {
  ROOT: "*",
  DEFAULT: "/",
  NOT_FOUND: "/not-found",
  LOGIN: "/login",
  REGISTER: "/register",
  HOME: "/home",
  REGION: "/region",
  TERRITORY: "/territory",
  PROVINCE: "/province",
  PLACE: "/place",
  POSTS: "/posts",
  POST_DETAIL: "/post-detail",
  POST_DETAIL_PREVIEW: "/post-detail-preview",
  UPLOAD_POST: "/upload-post",
  PROFILE: "/profile",
};
